### ISSUE TITLE
Plea to revert recent changes to singleton.hpp

### ISSUE THREAD

**Issue by tobias-loew** [boostorg/serialization#102]
This is a plea to revert all the changes recently done to singleton.hpp. The reasons for this plea are
- having to call destructors for singlons to prevent memory-leaks is very unusual and counter-intuitive
- using
       if (!t)
            t = new singleton_wrapper;
    in singleton::get_instance() is not thread-safe (the former code using a non-pointer static variable was thread-safe by design)
- The reason for all those changes is a non-standard-conforning implementation detail of the gcc-compiler. The so-called fix for the gcc-error was not a fix at all, but simple a memory-leak as the problematik pointer was never(!) deleted (and therefore the problem seemde to be fixed).
If not removed at all, then those changes should definitively be guarded by some gcc-workaround macro, that all other compilers use the old - and totally correct - code.

In my opinion those changes should be reverted as soon as possible and hopefully make it into Boost 1.67.

Tobias

**Comment by robertramey** [comment]
sorry I haven't been able to address this.  The reason is that fixing it properly has to going back and studying why we made the change in the first place.  If I don't do that, then we just end up playing whack-a-mole.  To prevent this, I usually try to get a test case which fails and add it to the test suite.  So the best would be if we had a small program which displays the existence of the memory leak.  Then we'll be sure it never comes back.  Then we have to fix it and test it on all the platforms we use.  That takes a while.  No way that this will be ready for 1.67.

What I recommend is that you either
a) role back your local copy to 1.65
b) edit your change into your local copy of 1.66 or 1.67

Hopefully we'll be able to fix this by 1.68

**Comment by tobias-loew** [comment]
I didn't have time to create  an example yet, but every code using BOOST_CLASS_EXPORT now has a memory-leak: BOOST_CLASS_EXPORT  expands BOOST_CLASS_EXPORT_IMPLEMENT and in there a singleton is instantiated. A haven't completely proved but I strongly doubt that for those instances the destructors get called.

#define BOOST_CLASS_EXPORT_IMPLEMENT(T)                      \
    namespace boost {                                        \
    namespace archive {                                      \
    namespace detail {                                       \
    namespace extra_detail {                                 \
    template<>                                               \
    struct init_guid< T > {                                  \
        static guid_initializer< T > const & g;              \
    };                                                       \
    guid_initializer< T > const & init_guid< T >::g =        \
        ::boost::serialization::singleton<                   \
            guid_initializer< T >                            \
        >::get_mutable_instance().export_guid();             \
    }}}}                                                     \

**Comment by tobias-loew** [comment]
There's also a Boost-bug connected to those changes https://svn.boost.org/trac10/ticket/13186

**Comment by robertramey** [comment]
I've reversed the commit that causes the problem.  It was done in haste.  Since it doesn't use heap memory any more, all such leaks should disappear.  Unfortunately, I still have an issue with test_dll_export which is what this change had "fixed".  On going.
