### ISSUE TITLE
Std container binary serialization doesn't use fixed width integer

### ISSUE THREAD

**Issue by SharpSnake** [boostorg/serialization#159]
For example, i serialize a std::string( std::vector and other containers have the same problem ) on x64 environment, and deserialize it on x86 environment always get a error result or exception.
Both use binary_i/oarchive.

This is caused by "size_t", which is the type of the container size.
Why not use a fixed width integer, like std::uint32_t?

**Comment by SharpSnake** [comment]
And is there a simple way to solve the problem? Thanks.
 @robertramey

**Comment by robertramey** [comment]
binary archives are not guaranteed to be portable.  That is the can only be guaranteed to be saved/loaded to the same machine architecture.  For portable storage, use a different archive - example text archive.

**Comment by SharpSnake** [comment]
Text and xml archive sure are options. But i prefer binary archives, it's smaller and faster for network transmission, for example.
Really looking forward to have some improvements for portable binary storage int the future version. Maybe we can custom config to use std::uint32_t or std::uint64_t on both sides of save/load.

**Comment by robertramey** [comment]
>Really looking forward to have some improvements for portable binary storage
This is the real solution.  There is a portable binary archive in the examples.  And there is a submitted one which has been around for many years and I understand often used. See EOS Portable Archive project.  Looked at integrating it into the official boost package but it turned out to be more effort than I had anticipated.  Anyway, it might be the exact solution your looking for.

**Comment by SharpSnake** [comment]
I found it, and i will look into this project later.
Thank you very much, sir.
