### ISSUE TITLE
s/&*/boost::addressof incomplete

### ISSUE THREAD

**Issue by joaquintides** [boostorg/serialization#80]
Hi Robert,

I see you've replaced occurrences of raw `&*t` with `boost::addressof(t)`, presumably to cope with types whose `operator&` is overloaded. This replacement is still not done at

https://github.com/boostorg/serialization/blob/8378c75f32b87c2ef8acf74b5ba6ec4dc2a78648/include/boost/serialization/collections_save_imp.hpp#L63

(at least). Thank you,

**Comment by alfC** [comment]
Yes, there at least three places that need that replacement. See here
https://github.com/boostorg/serialization/issues/72

On Nov 23, 2017 17:51, "joaquintides" <notifications@github.com> wrote:

Hi Robert,

I see you've replaced occurrences of raw &*t with boost::addressof(t),
presumably to cope with types whose operator& is overloaded. This
replacement is still not done at

https://github.com/boostorg/serialization/blob/
8378c75f32b87c2ef8acf74b5ba6ec4dc2a78648/include/boost/
serialization/collections_save_imp.hpp#L63

(at least). Thank you,

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/boostorg/serialization/issues/80>, or mute the thread
